set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

set -g mouse on
set -g set-clipboard on

set -g status-position top

unbind C-b
set -g prefix C-space
bind-key C-space send-prefix

unbind %
bind i split-window -h -c "#{pane_current_path}"
unbind '"'
bind u split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-K swap-pane -U
bind -n M-J swap-pane -D

bind -n C-M-h resize-pane -L 5
bind -n C-M-j resize-pane -D 5
bind -n C-M-k resize-pane -U 5
bind -n C-M-l resize-pane -R 5

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# move pane to window N
bind -n M-! move-pane -t :1
bind -n M-@ move-pane -t :2
bind -n M-# move-pane -t :3
bind -n M-$ move-pane -t :4
bind -n M-% move-pane -t :5
bind -n M-^ move-pane -t :6
bind -n M-& move-pane -t :7
bind -n M-* move-pane -t :8
bind -n M-( move-pane -t :9
bind -n M-) move-pane -t :0

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Custom Scripts and Popups
bind-key -r m display-popup -E "~/.local/bin/tmux-cht"

# Lazygit
bind-key -r g display-popup \
  -d "#{pane_current_path}" \
  -w 90% \
  -h 90% \
  -E "lazygit"

# Scratchpads
bind-key s display-popup -E -w 80% -h 70% "$SHELL"

##### STATUSLINE (transparent minimal white theme)

set -g status on
set -g status-style "bg=default"
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100

set -g message-style "fg=white,bg=default"
set -g message-command-style "fg=white,bg=default"

set -g pane-border-style "fg=white"
set -g pane-active-border-style "fg=blue"

set -g window-status-activity-style "fg=white,bg=default"
set -g window-status-separator ""
set -g window-status-style "fg=white,bg=default"

set -g window-status-current-format "#[fg=blue] #I #[fg=white]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev)"
set -g window-status-format "#[fg=white] #I #W"

set -g status-right "#[fg=blue] #[fg=white]#S"
set -g status-left ""

set -g clock-mode-colour blue
set -g mode-style "fg=blue bg=default bold"
